config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users,
   ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'pages#index'
  
  
  resources :paints
  resources :tags, only: [:show]
  resources :userparams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	belongs_to :paint
end

app/models/paint.rb
class Paint < ApplicationRecord
	belongs_to :user

    mount_uploader :picture, PicturesUploader
    has_one :category
    validates :user_id, :name, :description, :price, presence: true

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :userparam
         has_many :paints
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	belongs_to :user

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    
    validates :firstname, :lastname, :place, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :find
  def index
  	@q = Paint.search(params[:q])
    @paint =  @q.result(distinct: true)    
  end
  private
  def find 
   @paint = Paint.find_by(id: params[:id])

  end
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
   before_action :authenticate_user!
before_action :find, only:[:show, :edit, :update, :destroy]
  def index
    @q = Paint.search(params[:q])
    @paint =  @q.result(distinct: true)    
  end

  def new
    @paint = Paint.new
  end

  def create
    @paint = current_user.paints.build(paint_params)
      if @paint.save
       redirect_to root_path
      else
        render 'new'
      end
  end


  def show
    @userparam = Userparam.find_by(params[:id])
  end

  def edit
  end

  def update
    if @paint.update(paint_params)
      flash[:notice] = "Paint successfully updated"
      redirect_to root_path
    else
      flash[:error] = "Error"
      render 'edit'
    end

  end

  def destroy
    @paint.destroy
    redirect_to root_path
  end

private
  def paint_params
    params.require(:paint).permit(:user_id, :name, :description, :price, :picture, :category_id)
  end
  def find
    @paint = Paint.find_by(id: params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(name: params[:id])
		@paints = @tag.paints
	end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
before_action :authenticate_user!
before_action :find , only:[:show, :edit, :update]
  def new
    @userparam = Userparam.new
  end
  
  def create
    @userparam = current_user.build_userparam(profile_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    end
    
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @userparam.update(profile_params)
       redirect_to userparam_path(@userparam.id)
    end
    
  end
  
private

  def profile_params
    params.require(:userparam).permit(:user_id, :email, :firstname, :lastname, :place, :avatar)
  end
  def find
    @userparam = Userparam.find_by(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/layouts/_footer.html.erb
<center>2018</center>

app/views/layouts/_header.html.erb
<h4><p align="left"><% if user_signed_in? %>
  <%= link_to "Back", root_path %> |
 <%= link_to "Add new picture", new_paint_path%> |
  <% if current_user.userparam.nil? %>
     <%= link_to "Profile", new_userparam_path %></br>
  <% else %>
   <%= link_to "Profile", userparam_path(current_user.id) %>
  <% end %>
 </p>
<p align="right">


	<%= link_to "Logout",  destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "Login", new_user_session_path %>
<% end %>
</p></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Masterpiece</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
  <hr>
  <% if user_signed_in? %>
  
  <% end %>
    <%= yield %>
     <hr> 
     <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/index.html.erb
<center><h2>Hi! If you looking for a masterpiece, this site is special for you!</br> </h2></center>
		<p align="right"><%= search_form_for @q do |f| %>
  <%= f.search_field :name_cont %>
  <%= f.submit "Found" %>
  <% end %></p> 

    

<center><% @paint.each do |paint| %>
	<p>	<%= image_tag(paint.picture_url, size: "150x200")%><br>
       	<b><%= paint.name %></b><br />
       <b><%= paint.description %></b><br />
       Price: <%= paint.price %>$</br>
       <%=link_to "Buy", paint_path(paint.id)%>
        <% if user_signed_in? && paint.user_id == current_user.id%></br>
       <%= link_to "Read More", edit_paint_path(paint.id) %></p>
    <% end %>
    <%end%>
</center> 	

app/views/paints/edit.html.erb
<%= form_for @paint, url: paint_path(@paint.id) do |f| %>
  Name: <%= f.text_field :name %><br />
  <%= f.select :category_id  , Category.all.collect {|p| [ p.name, p.id ]}, :prompt => 'Choose a Category'%> <br>
  Description: <%= f.text_area :description, size: "60x12" %><br />
   Price: <%= f.text_field :price %><br />
  <%= f.submit "Create" %>  |
  <%= link_to "Delete", paint_path(@paint.id), method: :delete %><br /></p>
<% end %>

app/views/paints/index.html.erb
	<p align="right"><%= search_form_for @q do |f| %>
  <%= f.search_field :name_cont %>
  <%= f.submit "Found" %>
  <% end %></p> 
  <center><% @paint.each do |paint| %>

<p>	<%= image_tag(paint.picture_url, size: "150x200")%><br>
       	<b><%= paint.name %></b><br />
       <b><%= paint.description %></b><br />
       Price: <%= paint.price %>$</br>
       <%=link_to "Buy", paint_path(paint.id)%>
        <% if user_signed_in? && paint.user_id == current_user.id%></br>
       <%= link_to "Read More", edit_paint_path(paint.id) %></p>
    <% end %>
    <%end%>
</center>
    

app/views/paints/new.html.erb
<%= form_for @paint, url: paints_path do |f| %>

<% if @paint.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@paint.errors.count, "error") %>
     saved:</h2>
 
    <ul>
    <% @paint.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p>Name: <%= f.text_field :name %><br />
    <%= f.select :category_id  , Category.all.collect {|p| [ p.name, p.id ]}, :prompt => 'Choose a Category'%> <br>`
  Description: <%= f.text_area :description, size: "60x10" %><br />
  Price: <%= f.text_field :price%></br>
  <%= f.file_field :picture %>
 
  <%= f.submit "Add" %>
<% end %>

app/views/paints/show.html.erb
	<%= image_tag(@paint.picture_url, size: "150x200")%> <br>
	<b><%= @paint.name %></b><br />
	Category: <%= Category.find_by(id: @paint.category_id).try(:name) %> <br>
       <b><%= @paint.description %></b><br />
       Price: <%= @paint.price %>$</br>
     By user:    <%= link_to @paint.user.email.split('@').first, userparam_path(@userparam.id) %>
     

app/views/userparams/edit.html.erb
<%= form_for @userparam, url: userparam_path(current_user.id) do |f| %>
  Firsname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Place: <%= f.text_field :place %><br />
	     <%= f.file_field :avatar %>
  <%= f.submit "Update" %>
<% end %>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: {action: "create"} do |f| %>

<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Email: <%= f.text_field :email %><br />
  Firsname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Place: <%= f.text_field :place %><br />
  <%= f.file_field :avatar %>
  <%= f.submit "Create" %>
<% end %>

app/views/userparams/show.html.erb
<%= image_tag current_user.userparam.avatar.url(:thumb) %><br />
Email: <%= current_user.userparam.email %><br />
Firstname: <%= current_user.userparam.firstname %><br />
Lastname: <%= current_user.userparam.lastname %><br />
Place: <%= current_user.userparam.place %><br />
<%= link_to "edit", edit_userparam_path(current_user.id) %><br />